---
output: pdf
---

# Abstract {-}

Urban trees provide numerous benefits, ranging from aesthetic and environmental to psychological and economical. Tree health is a critical part of urban ecosystem function, and is closely tied to the benefits or lack thereof that urban trees can provide. 
With over one million trees in Portland's urban forest, conducting field health assessments to understand the dynamics of tree health in Portland is a nearly impossible goal. 
Due to the size of urban forests and the time consuming practice of field health assessments, recent research into tree health has turned to satellite imagery as a tool for evaluating tree health. 
This thesis looks to examine the health ratings of four key tree species in Portland (Acer macrophyllum, Acer platanoides, Pseudotsuga menziesii, and Thuja plicata) from field data collected in the summer of 2021, and the relationship between health rating and NDVI (Normalized Difference Vegetation Index), which is an index of "greenness" commonly used in remote sensing of vegetation. 
This thesis tests three different tree canopy delineation and pixel selection techniques for obtaining NDVI to determine which is the most effective for obtaining tree health information and predicting health rating from NDVI. 
I used an ordinal logistic regression model to predict health ratings of poor, fair or good. These predictions were based on 1) NDVI, 2) NDVI and tree functional type, or 3) NDVI and tree species. The impact of including either tree functional type or tree species in the predictive health model was examined. The most effective predictive model differentiated the predictions by species, and used the LiDAR data. This final model was most effective for the two maple species (ACMA and ACPL), categorizing trees in all three health categories for ACMA, and two health categories for ACPL. 
The model was ineffective for predicting the health ratings for conifer species.